import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Nav from '@/app/components/Nav'
import NProgressProvider from '@/app/components/NProgressProvider'

import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  metadataBase: new URL('https://nba-scores.web.app'),
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon/favicon.ico',
    shortcut: '/favicon/favicon.ico',
    apple: [
      {
        url: '/favicon/apple-touch-icon.png',
        sizes: '180x180',
        type: 'image/png',
      },
    ],
    other: [
      {
        rel: 'icon',
        type: 'image/png',
        url: '/favicon/favicon.ico',
        sizes: '16x16',
      },
      {
        rel: 'icon',
        type: 'image/png',
        url: '/favicon/favicon-32x32.png',
        sizes: '32x32',
      },
    ],
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NProgressProvider>
          <Nav />
          <main className="container mx-auto flex flex-grow flex-col px-4">
            {children}
          </main>
        </NProgressProvider>
      </body>
    </html>
  )
}
