import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import NProgressProvider from '@/app/components/NProgressProvider'

import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  metadataBase: new URL('https://nba-scores.web.app'),
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NProgressProvider>
          <main className="container mx-auto flex flex-grow flex-col px-4">
            {children}
          </main>
        </NProgressProvider>
      </body>
    </html>
  )
}
